# Generated by Django 2.1.5 on 2019-01-09 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entity_id',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('entity_id', 'effective', 'created')},
        ),
    ]
