# Generated by Django 2.1.5 on 2019-01-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_person_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='addresses',
            new_name='address_entity_ids',
        ),
    ]
